name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        go-version: ['1.20']
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          GOOS=windows GOARCH=amd64 go build -o EasyMemberManager.exe ./...
        else
          GOOS=linux GOARCH=amd64 go build -o EasyMemberManager ./...
        fi

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binary-${{ matrix.os }}
        path: myapp*

